image: Ubuntu

environment:
    nodejs_version: 11.0.0

platform:
    - x64

install:
    - npm install --production

# defined specific build configs for different branches
for:
-
    branches:
        only:
            - master
    build_script:
        - npm run publish-production
-
    branches:
        only:
            - develop
    build_script:
        - npm run publish-stage

# This will build based on `CONFIG` environment variable

version: "{build}"

skip_tags: true

branches:
    only:
        - master
        - develop
