image: Ubuntu1804

platform:
    - x64

install:
    - nvm use v11
    - npm ci --only=production
    - npm install --production

# defined specific build configs for different branches
for:
-
    branches:
        only:
            - master
    build_script:
        - npm run publish-production
-
    branches:
        only:
            - develop
    build_script:
        - npm run publish-stage
-
    branches:
        only:
            - /feature*/
    environment:
        S3_BUCKET: strawbees-test
    build_script:
        - npm run publish-stage

# This will build based on `CONFIG` environment variable

version: "{build}"

skip_tags: true

branches:
    only:
        - master
        - develop
        - /feature*/
